name: Build and Release

on:
  push:
    tags:
      - 'v*'


jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install C++ and OpenGL dependencies
        run: |
          sudo apt-get install -y freeglut3-dev libglew-dev libgl1-mesa-dev libglm-dev build-essential

      - name: Compile the project
        run: make

      - name: Prepare for the release
        run: |
          mkdir build_output
          cp main.exe build_output/
          # Add other assets (es. shader, texture)
          cp -r ./textures build_output/ 2>/dev/null || true
          cp -r ./shaders build_output/ 2>/dev/null || true
          tar -czvf app-linux-x86_64.tar.gz -C build_output .

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: app-linux-x86_64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MSYS2 / MinGW 32-bit
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          update: true
          install: >-
            mingw-w64-i686-gcc
            make

      - name: Compile the project
        shell: msys2 {0}
        run: |
          make

      - name: Prepare release package (Zip)
        shell: bash
        run: |
          mkdir build_output
          cp main.exe build_output/
          cp base/freeglut/bin/freeglut.dll build_output/ 2>/dev/null || true
          cp base/glew/bin/Release/Win32/glew32.dll build_output/ 2>/dev/null || true
          cp -r ./textures build_output/ 2>/dev/null || true
          cp -r ./shaders build_output/ 2>/dev/null || true

      - name: Archive build artifacts
        shell: pwsh
        run: |
          Compress-Archive -Path build_output\* -DestinationPath app-windows-x86.zip

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: app-windows-x86.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}